import os

import openai
from dotenv import load_dotenv
from signalbot import Command, Context

load_dotenv()


class GPT3Command(Command):
    def describe(self) -> str:
        return "Takes your message and gives a reply generated by GPT-3"

    async def handle(self, c: Context):
        await c.start_typing()
        openai.organization = os.environ.get("OPENAI_ORGANIZATION")
        openai.api_key = os.environ.get("OPENAI_API_KEY")

        x = openai.Completion.create(
            **{
                "model": "text-davinci-003",
                "prompt": f"Antworte sarkastisch: {c.message.text}",
                "max_tokens": 50,
            }
        )
        reply = x.choices[0].text.split("\n\n")[-1]
        await c.stop_typing()
        await c.send(f"{reply}")
